timezone: America/Sao_Paulo

exclude: [Gemfile, Gemfile.lock, LICENSE.md, README.md]

permalink: "/:title"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      lang: "pt-BR"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"

kramdown:
  input: GFM

highlighter: rouge

gems: [jemoji]
